
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: upload_arquivo_development

test:
  <<: *default
  database: upload_arquivo_test


production:
  primary: &primary_production
    <<: *default
    database: upload_arquivo_production
    username: upload_arquivo
    password: <%= ENV["UPLOAD_ARQUIVO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: upload_arquivo_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: upload_arquivo_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: upload_arquivo_production_cable
    migrations_paths: db/cable_migrate
